### ISSUE TITLE
Sign assembly

### ISSUE THREAD

**Issue by Corniel** [cbaxter/JSTest.NET#13]
There are (a lot?) build environments that require signed assemblies. In that case, it is not possible to run tests that require JSTest.NET. Is it possible to sign the delivery assembly?

**Comment by cbaxter** [comment]
@Corniel Absolutely, I will sign the assemblies today or tomorrow and update the NuGet packages.

**Comment by Corniel** [comment]
Wow, what a quick response! :) Thanx

**Comment by cbaxter** [comment]
Updated  [NuGet](https://www.nuget.org) packages for [JSTest](https://www.nuget.org/packages/JSTest.NET/1.1.1) and [JSTest.Integration.Xunit](https://www.nuget.org/packages/JSTest.Integration.Xunit/1.1.1). 

**Public Key**

```
0024000004800000940000000602000000240000525341310004000001000100c56817589b5329
264ab3c8911ca4b5e8f415b550f2037083294a2aa8dec8fc0bd9782c2ce1cc910a7bce4e897925
8d057f062e321daa88034abdb9d5d240453dd1c2e22862fec35d64c93e3622ad71be21f93d98d1
505944dfce9ad39c96d642d658987ed4822e54869bc1bce449df54bb45fb002cf5b43b3bb1d2aa
bc1492c2
```

_NOTE: xUnit packages updated to version 1.9.2_
