### ISSUE TITLE
Javascript function referencing another javascript file

### ISSUE THREAD

**Issue by leeh14** [cbaxter/JSTest.NET#15]
For the TestScript object I appended both javascipt files.  I'm running a unit test on javascript file A. In javascript file A it calls a function on Javscript file B. It seems as though the unit test was unable to find the function in Javscript file B and thus crashes the unit test. Am I doing something wrong? I thought all I had to do was make sure that the TestScript object needed to append both files to  it before running?

**Comment by cbaxter** [comment]
@leeh14 Sorry for the delayed reply, I have been without internet for a few days...

Yes, you should simply need to append multiple files to the TestScript object as shown in the [Wiki](https://github.com/cbaxter/JSTest.NET/wiki). Do you have a specific code sample you can provide?

**Comment by leeh14** [comment]
Thank you for the response it turned out that I was getting a null reference error and the file was indeed being loaded. It was just the wrong file and I didn't realize it at the time.
