### ISSUE TITLE
Unclear error of JsScript.exe

### ISSUE THREAD

**Issue by Corniel** [cbaxter/JSTest.NET#9]
The following test results in a "Microsoft Console Based Script Host has stopped working" pop-up message. Debugging it with the source code did not gave me extra insides.

Running the Javascript both in IE and Firefox is doing fine. I guess that it has something to do with adding the eq() to 'this'. The error occurs (while debugging) when entering the eq(12, 12) expression, not during the call to the anonymous (init) function call.  

``` C#
[TestMethod]
public void ShouldNotFail()
{
    var ctx = new TestScript();
    ctx.AppendBlock(@"
(function (cx) {
/**
* Compares the left and right operand on equality.
* @param {object} l The left operand.
* @param {object} r The right operand.
* @return True if the left operand equals the right operand, otherwise false.
*/
var eq = function (l, r) {
if (arguments.length !== 2) { throw new Error('Invalid number of arguments.'); }
if (l !== null && l !== 'undefined' && typeof (l['eq']) === 'function') {
    return l.eq(r);
}
if (r !== null && r !== 'undefined' && typeof (r['eq']) === 'function') {
    return r.eq(l);
}
return l === r;
};

cx.eq = eq;
})(this);");

    ctx.RunTest(@"
    var self = this;
    var exp = 12 === 12;
    var act = eq(12, 12);");
}
```

**Comment by cbaxter** [comment]
Thank you for the detail, I will try to investigate later today or at the very least tomorrow.

**Comment by cbaxter** [comment]
@Corniel I have started to investigate the issue. As you have pointed out, the lack of an exception message when the process exits with a non-zero exit code and no standard output is not particularly helpful. To that end, I will update the exception thrown from:

```
throw new ScriptException(standardOutput.ToString());
```

to:

```
error = standardOutput.ToString();
if (String.IsNullOrEmpty(error))
    error = String.Format("{{\"message\":\"Unknown error\",\"number\":{0},\"description\":\"Unknown error\"}}", proc.ExitCode);

throw new ScriptException(error);
```

The exit code returned from your test case is `-1073741819` which is an `Access Violation`. There are some documented issues around CScript 5.8 with at least one potentially related hot-fix (i.e., http://support.microsoft.com/kb/2706051). Unfortunately, that won't resolve this issue you are seeing.

Replacing `this` with some other object works fine; but obviously that is not what you are looking for. I am thinking of options to re-define `this` in the context of a test case, just have to figure out the best way to deal with `include` files. I will keep you posted.

**Comment by cbaxter** [comment]
@Corniel Funny I have never run in to this over the past five years... this appears to be a limitation of CScript in that functions explicitly added to WSH `this` are not invokable. 

As mentioned, I have actually never run in to this issue myself; I typically have taken one of two paths:

1) If I must declare a true global function, then I don't bother with an anonymous wrapper function (it _is_ global after all):

``` C#
ctx.AppendBlock(@"
function eq(l, r) {
    //if (arguments.length !== 2) { throw new Error('Invalid number of arguments.'); }
    if (l !== null && l !== 'undefined' && typeof (l['eq']) === 'function') {
        return l.eq(r);
    }
    if (r !== null && r !== 'undefined' && typeof (r['eq']) === 'function') {
        return r.eq(l);
    }
    return l === r;
};
");
```

2) My preferred approach is to not pollute the global namespace, thus like most libraries, I add my own `namespace` object (i.e., $, ko, assert, etc). 

``` C#
ctx.AppendBlock(@"
(function (window) {
  var myNamespace = window.myNamespace = (window.myNamespace || {});

  myNamespace.eq = function (l, r) {
    //if (arguments.length !== 2) { throw new Error('Invalid number of arguments.'); }
    if (l !== null && l !== 'undefined' && typeof (l['eq']) === 'function') {
        return l.eq(r);
    }
    if (r !== null && r !== 'undefined' && typeof (r['eq']) === 'function') {
        return r.eq(l);
    }
    return l === r;
  };
})(this)
");
```

After giving it some thought, I think it would be dangerous for JSTest to try and change the context of `this` for `ScriptBlocks` given that `ScriptIncludes` may also reference the global object and thus they would end up seeing something different as a result. 

Any input would be appreciated.

**Comment by Corniel** [comment]
@cbaxter It totally obvious to me that changing the this context is not the way to go. But as you pointed out the exception was not helpful. So fixing the response is good start. Thanks!

Although you can argue that introducing namespaces in JS is a good thing (and I guess we agree on that) in this case I decided I don't want to. As operator overloading is not possible, I'm searching for the next best thing. So short notation and elegance are required.

As developer I don't like to change my implementation because (only) my test framework don't accepts it. In this case, I will reconsider my implementation anyway, but more general I think its a good thing to describe this (use)case at the wiki, so that other developers can be convinced that the use of this construction leads to an error, _but_ that there are other good reasons not to opt for this syntax.

In the end, the use of a testing framework should improve the code. :)

**Comment by cbaxter** [comment]
@Corniel Thanks for the feedback. I will create an updated NuGet package in the near future with the modified exception reporting. I have also asked a question on [StackOverflow](http://stackoverflow.com/questions/13906025/unable-to-invoke-function-explicitly-added-to-global-this) to see if anyone can provide more insight as to why this is disallowed (although I am not expecting an answer).

As for the suggestion of a wiki page on the subject; that is also a good idea and will write something up when I update the NuGet packages.

**Comment by cbaxter** [comment]
Common Errors wiki page added: https://github.com/cbaxter/JSTest.NET/wiki/Common-Errors
NuGet packages updated: https://nuget.org/packages/JSTest.NET
